### ISSUE TITLE
support for lowerbound and upperbound

### ISSUE THREAD

**Issue by bulaiden** [datastructures-js/binary-search-tree#27]
are there plans to support lowerbound and upperbound methods for the BSTs?

reference:
http://www.cplusplus.com/reference/map/map/lower_bound/
http://www.cplusplus.com/reference/map/map/upper_bound/

**Comment by eyas-ranjous** [comment]
@bulaiden thanks for your input and sorry for the delay. I will read about this feature to evaluate if it's possible to add it to the base general purpose tree. Cheers
