### ISSUE TITLE
Node value is not updated when removing node in binarySearchTree.js

### ISSUE THREAD

**Issue by abhvsn** [datastructures-js/binary-search-tree#29]
Remove method with 2 children in binarySearchTree.js is basically updating the key but value still remains the same as the node which needs to be removed is this intended? Check the following snippet 
```
const minRight = this.min(node.getRight());
node.setKey(minRight.getKey());
return this.remove(minRight.getKey(), minRight);
```

**Comment by eyas-ranjous** [comment]
hi @abhvsn sorry for the late reply. good catch, yes it's missing updating the value of the removed node. will push fix shortly.
