### ISSUE TITLE
Some TS types should be nullable 

### ISSUE THREAD

**Issue by banacorn** [datastructures-js/binary-search-tree#45]
Some function returns `null`:

```js
console.log(bst.lowerBound(60).getKey()); // 60
console.log(bst.lowerBound(60, false).getKey()); // 50
console.log(bst.lowerBound(10)); // null
```

However, this is not reflected in the TS type definition file

https://github.com/datastructures-js/binary-search-tree/blob/74e9a83f8799e39a659a2c205884cc06c43aa770/src/binarySearchTree.d.ts#L9

**Comment by eyas-ranjous** [comment]
Thanks for reporting @banacorn I I'll fix this soon.
