### ISSUE TITLE
Add support for a custom comparator function.

### ISSUE THREAD

**Issue by segevfiner** [datastructures-js/binary-search-tree#49]
Keys are currently compared using `<`, it would be nice to be able to specify a custom comparison function for cases where you want to use the tree as a set and need to key values in a different way.

It would be also interesting to create some version/optimization for this cases in terms of only having a key without a value.

P.S. Some methods of `AvlTree` such as `getLeft`/`getRight` end up returning `BinarySearchTreeNode` instead of `AvlTreeNode`.

**Comment by eyas-ranjous** [comment]
v5.0.0 released https://github.com/datastructures-js/binary-search-tree#constructor

**Comment by eyas-ranjous** [comment]
v5.0.0 released v5.0.0 released https://github.com/datastructures-js/binary-search-tree#contents

**Comment by eyas-ranjous** [comment]
v5.0.0 released https://github.com/datastructures-js/binary-search-tree#contents
