### ISSUE TITLE
Change to V5: need to have object to check whether it is in BST

### ISSUE THREAD

**Issue by JeroenClijmans** [datastructures-js/binary-search-tree#54]
Since the update to V5, the interface has changed a lot. However, I don't think some changes are beneficial.
Most notably, it seems that the binary search tree no longer works in key-value pairs. As an example, where you would previously use the 'has' method to look whether a particular key is present in the tree, this method now requires you to provide a particular object. This takes away a lot of functionality from this package? I used this package to implement a tiny little custom cache, so when I want to look up an object, I only know the key used to store it and not the object itself. Since the update to V5, such lookup is no longer possible and therefore I can no longer use this package.
I wonder what is the reasoning behind this change?

**Comment by eyas-ranjous** [comment]
thanks for the feedback. The reason for the upgrade was to provide the ability to use custom compare functions between nodes. key-value way is rigid and does not allow complex comparison logic beyond the key. However, I will add an improvement to allow searching key only. despite working with objects. tagging your request as enhancement.
